### ISSUE TITLE
use private go modules

### ISSUE THREAD

**Issue by hrdtbs** [hrdtbs/workflows#15]
```yml
name: Generate endpoints.json

on:
  pull_request:
    paths:
      - web/init.go

jobs:
  generate-endpoints-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Set github private modules access
        run: git config --global url."https://${{ secrets.REPO_ONLY_GITHUB_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
      - uses: actions/setup-go@v3
        with:
          go-version-file: "./go.mod"
      - name: Generate .endpoints.json
        run:  go run main.go
      - name: Check diff
        id: diff
        run: |
          git add -N .
          git diff --name-only --exit-code .endpoints.json
        continue-on-error: true
      - name: Commit & Push
        run: |
          set -x
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m 'chore: update .endpoints.json'
          git push
        if: steps.diff.outcome == 'failure'


```
